apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cluster-object
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - local-cluster
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch